# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vscode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vscode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vscode/CMakeFiles /vscode/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vscode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named STM32G031K8_.elf

# Build rule for target.
STM32G031K8_.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STM32G031K8_.elf
.PHONY : STM32G031K8_.elf

# fast build rule for target.
STM32G031K8_.elf/fast:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/build
.PHONY : STM32G031K8_.elf/fast

Core/Src/gpio.o: Core/Src/gpio.c.o

.PHONY : Core/Src/gpio.o

# target to build an object file
Core/Src/gpio.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/gpio.c.o
.PHONY : Core/Src/gpio.c.o

Core/Src/gpio.i: Core/Src/gpio.c.i

.PHONY : Core/Src/gpio.i

# target to preprocess a source file
Core/Src/gpio.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/gpio.c.i
.PHONY : Core/Src/gpio.c.i

Core/Src/gpio.s: Core/Src/gpio.c.s

.PHONY : Core/Src/gpio.s

# target to generate assembly for a file
Core/Src/gpio.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/gpio.c.s
.PHONY : Core/Src/gpio.c.s

Core/Src/main.o: Core/Src/main.c.o

.PHONY : Core/Src/main.o

# target to build an object file
Core/Src/main.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/main.c.o
.PHONY : Core/Src/main.c.o

Core/Src/main.i: Core/Src/main.c.i

.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/main.c.i
.PHONY : Core/Src/main.c.i

Core/Src/main.s: Core/Src/main.c.s

.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/main.c.s
.PHONY : Core/Src/main.c.s

Core/Src/stm32g0xx_it.o: Core/Src/stm32g0xx_it.c.o

.PHONY : Core/Src/stm32g0xx_it.o

# target to build an object file
Core/Src/stm32g0xx_it.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/stm32g0xx_it.c.o
.PHONY : Core/Src/stm32g0xx_it.c.o

Core/Src/stm32g0xx_it.i: Core/Src/stm32g0xx_it.c.i

.PHONY : Core/Src/stm32g0xx_it.i

# target to preprocess a source file
Core/Src/stm32g0xx_it.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/stm32g0xx_it.c.i
.PHONY : Core/Src/stm32g0xx_it.c.i

Core/Src/stm32g0xx_it.s: Core/Src/stm32g0xx_it.c.s

.PHONY : Core/Src/stm32g0xx_it.s

# target to generate assembly for a file
Core/Src/stm32g0xx_it.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/stm32g0xx_it.c.s
.PHONY : Core/Src/stm32g0xx_it.c.s

Core/Src/usart.o: Core/Src/usart.c.o

.PHONY : Core/Src/usart.o

# target to build an object file
Core/Src/usart.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/usart.c.o
.PHONY : Core/Src/usart.c.o

Core/Src/usart.i: Core/Src/usart.c.i

.PHONY : Core/Src/usart.i

# target to preprocess a source file
Core/Src/usart.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/usart.c.i
.PHONY : Core/Src/usart.c.i

Core/Src/usart.s: Core/Src/usart.c.s

.PHONY : Core/Src/usart.s

# target to generate assembly for a file
Core/Src/usart.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Core/Src/usart.c.s
.PHONY : Core/Src/usart.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c.s

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.o: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.o

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.o

# target to build an object file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.o
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.o

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.i: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.i

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.i

# target to preprocess a source file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.i:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.i
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.i

Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.s: Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.s

.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.s

# target to generate assembly for a file
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.s:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.s
.PHONY : Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c.s

startup_stm32g031xx.o: startup_stm32g031xx.s.o

.PHONY : startup_stm32g031xx.o

# target to build an object file
startup_stm32g031xx.s.o:
	$(MAKE) -f CMakeFiles/STM32G031K8_.elf.dir/build.make CMakeFiles/STM32G031K8_.elf.dir/startup_stm32g031xx.s.o
.PHONY : startup_stm32g031xx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... STM32G031K8_.elf"
	@echo "... Core/Src/gpio.o"
	@echo "... Core/Src/gpio.i"
	@echo "... Core/Src/gpio.s"
	@echo "... Core/Src/main.o"
	@echo "... Core/Src/main.i"
	@echo "... Core/Src/main.s"
	@echo "... Core/Src/stm32g0xx_it.o"
	@echo "... Core/Src/stm32g0xx_it.i"
	@echo "... Core/Src/stm32g0xx_it.s"
	@echo "... Core/Src/usart.o"
	@echo "... Core/Src/usart.i"
	@echo "... Core/Src/usart.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_pwr.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.s"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.o"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.i"
	@echo "... Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.s"
	@echo "... startup_stm32g031xx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

